### ISSUE TITLE
[Improvement] Explain command line options 

### ISSUE THREAD

**Issue by Mooibroek** [fadhilx/json_to_model#3]
**Is your feature request related to a problem? Please describe.**
I noticed that there are 3 options available while browsing the source, but missed the explanations in the documentation

**Describe the solution you'd like**
Add them to the docs :-D

If I have some time the upcomming week i'll try to create a PR to add this.

**Comment by fadhilx** [comment]
thanks for telling me that, i aware that there is feature missing in the docs, maybe because i don't think the feature ready to be introduced or it not tested well or i just dont have time for that(maybe its not in my priority yet), but you can still contribute to the docs. i quite busy these days, maybe next week i will try to comeback to open source project, 

thanks
